---
title: "ASM_project_louis"
output: html_document
date: '2022-12-25'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data

Data from 1997 until 2022 of flu. 
pre.who is all combined cases up to 2015-16. who.clinical and who.public represent cases after 2015 with the former counting Clinical Lab positives and the latter counting results of the Public Health Labs. These will later be combined into one. 

```{r}
pre.who = read.csv("WHO_NREVSS_Combined_prior_to_2015_16.csv", header=TRUE, skip=1) 
head(pre.who)

who.clinical = read.csv("WHO_NREVSS_Clinical_Labs.csv", header=TRUE, skip=1)
head(who.clinical)

who.public = read.csv("WHO_NREVSS_Public_Health_Labs.csv", header=TRUE, skip=1)
head(who.public)
```


```{r}
pre.who.clean = pre.who %>%
  filter(YEAR > 1997) %>%
  mutate(DATE=sprintf("%s_%02d", YEAR, WEEK)) %>%
  mutate(INF_ALL=ceiling(TOTAL.SPECIMENS * PERCENT.POSITIVE / 100)) %>%
  filter(WEEK < 53) %>%
  select(c(DATE, WEEK, INF_ALL)) %>%
  arrange(DATE) # Until 2015_39

head(pre.who.clean)
#table(pre.who.clean$WEEK) # Complete data

who.clinical.clean = who.clinical %>% # From 2015_40 onwards
  mutate(DATE=sprintf("%s_%02d", YEAR, WEEK)) %>% 
  mutate(INF_ALL=ceiling(TOTAL.SPECIMENS * PERCENT.POSITIVE / 100)) %>%
  filter(WEEK < 53) %>%
  select(c(DATE, WEEK, INF_ALL)) %>%
  arrange(DATE)

head(who.clinical.clean) # Complete data

flu.strains = c("A..2009.H1N1.", "A..H3.", "A..Subtyping.not.Performed.", "B", "BVic", "BYam", "H3N2v")
who.public.clean = who.public %>%
  mutate(DATE=sprintf("%s_%02d", YEAR, WEEK)) %>% 
  mutate(INF_ALL=rowSums(across(all_of(flu.strains)))) %>%
  filter(WEEK < 53) %>%
  select(c(DATE, WEEK, INF_ALL)) %>%
  arrange(DATE)

head(who.public.clean) # Complete data

post.who.clean = who.clincal.clean %>%
  left_join(who.public.clean, by="DATE") %>%
  mutate(INF_ALL=INF_ALL.x + INF_ALL.y) %>%
  select(DATE, INF_ALL)

head(post.who.clean)

flu.usa = pre.who.clean %>%
  select(DATE, INF_ALL) %>%
  bind_rows(post.who.clean) %>%
  mutate(DATE=as.Date(paste(flu.usa$DATE,"1", sep = "_"), '%Y_%U_%w'))

flu.usa
```

```{r}
flu.usa.ts = ts(flu.usa$INF_ALL, start=1998, frequency=52)
serie = flu.usa.ts
```

```{r}
par(mfrow=c(1,2))
plot(serie)
abline(v=1990:2020,col=4,lty=3)
plot(log(serie))
abline(v=1990:2020,col=4,lty=3)
```
```{r}
boxplot(serie~floor(time(serie)))
```
```{r}
boxplot(log(serie+1)~floor(time(serie))) #Do log(x+1) transformation to evade exploding log of zero values. 
```

```{r}
mserie = matrix(serie, ncol=52, byrow=TRUE)
m = apply(mserie, 1, mean) #Calculate Mean for each year
v = apply(mserie, 1, var) #Calculate Variance for each year
plot(v ~ m)
abline(lm(v ~ m), col=2, lty=3)
```

```{r}
lnserie <- log(serie + 1)
```

```{r}
monthplot(lnserie)
```
```{r}
ts.plot(matrix(lnserie, nrow=52))
```


```{r}
d52lnserie <- diff(lnserie,52)
plot(d52lnserie)
abline(h=0)
```

```{r}
monthplot(d52lnserie)
```

```{r}
d1d52lnserie <- diff(d52lnserie)
plot(d1d52lnserie)
abline(h=0)
```

```{r}
d1d1d52lnserie <- diff(d1d52lnserie)
plot(d1d1d52lnserie)
abline(h=0)
```
```{r}
var(lnserie)
var(d52lnserie)
var(d1d52lnserie)
var(d1d1d52lnserie)
```

```{r}
par(mfrow=c(1,2))
acf(d1d52lnserie, ylim=c(-1,1), lag.max = 71,col=c(2,rep(1,51)),lwd=2) #What to choose as lag.max??... 
pacf(d1d52lnserie, ylim=c(-1,1), lag.max = 71,col=c(rep(1,51),2),lwd=2) #Have to go do some Xmass nonesense right now.
par(mfrow=c(1,1))
```


